### PR TITLE
Added Vocab & Updated Video Display

### PR DESCRIPTION
**Pull request by crmilsap**
Added Vocabulary for each user and updated the video display list to be more reactive for various screen sizes.

https://user-images.githubusercontent.com/47369429/144082694-9a2ac2c9-d84f-4969-8f58-ab12af6ce412.mov

### CODE REVIEW

**Comment by NoahZielke** [comment]
https://user-images.githubusercontent.com/22875039/144084868-ad97c1ad-d6b1-48ac-b2d0-c359221956a3.mp4
Is this expected behavior?

**Comment by crmilsap** [comment]
No that shouldn't happen. It's working fine for me. Could you try again?

**Comment by crmilsap** [comment]
https://user-images.githubusercontent.com/47369429/144086817-536174bf-e29a-4960-a8b8-fb9887a1c283.mov

**Comment by NoahZielke** [comment]
https://user-images.githubusercontent.com/22875039/144086909-0871fc3b-1463-4dbe-a5a3-de9f3e596540.mp4

Yeah I think I found what triggers the bug? Still testing

**Comment by NoahZielke** [comment]
Closed by mistake, reopened

**Comment by NoahZielke** [comment]
Actually what I posted above seems to be a different bug. I don't remember how I triggered the deleting vocab one.

**Comment by crmilsap** [comment]
The console should have more details about the requests happening for adding words. If you find out how to replicate the bug let me know. I will try to find as well but it is difficult as add/create works on my end.

**Comment by crmilsap** [comment]
There are troubles in the backend with delete_vocab. It doesn't work in Postman either.

**Comment by crmilsap** [comment]
I believe the default values fail on the backend due to the space or number

**Comment by crmilsap** [comment]
I changed the default value to be "Word"

**Comment by NoahZielke** [comment]
https://user-images.githubusercontent.com/22875039/144090738-2973fca3-3d44-4332-992d-e77ead76b628.mp4

1 - It seems that it won't let you add the same word twice, but only within the same session. That is, I can add "word" 100 times if I sign out each time
2 - Still getting some weird behavior

**Comment by crmilsap** [comment]
Hmm that is strange behavior. Can you try registering a new user and using that. I had had to do that yesterday after the server was reset. Only reason I can think that of for getting different behavior

**Comment by NoahZielke** [comment]
> Hmm that is strange behavior. Can you try registering a new user and using that. I had had to do that yesterday after the server was reset. Only reason I can think that of for getting different behavior

In reality, we have less than 3 hours so it's not wise to go bug smashing now. Let's just merge this and I'll have to keep the demo of this very "on-rails".

**Comment by crmilsap** [comment]
Okay try logging into user test2@test.com with password testtest. That was the user I was using and it was behaving as expected for me

**Pull request merged**
